name: Create new Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'v')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        npm install
        npm install typescript --save-dev

    - name: Read version from manifest
      id: get_version
      run: |
        version=$(jq -r '.header.version | map(tostring) | join(".")' manifest.json)
        echo "Version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Create MCPack
      run: |
        npx ts-node --project tsconfig.json scripts/build.ts

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        name: "v${{ steps.get_version.outputs.version }}"
        tag_name: "v${{ steps.get_version.outputs.version }}"
        files: |
          PokeBedrock RES ${{ steps.get_version.outputs.version }}.mcpack
          PokeBedrock RES ${{ steps.get_version.outputs.version }}.zip
        draft: false

    - name: Read CHANGELOG.md
      id: read_changelog
      run: |
        changelog=$(cat CHANGELOG.md)
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$changelog" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Set Release URL
      id: set_release_url
      run: echo "release_url=https://github.com/${{ github.repository }}/releases/tag/v${{ steps.get_version.outputs.version }}" >> $GITHUB_OUTPUT

    - name: Complete Workflow
      run: echo "Workflow completed successfully."
